// <auto-generated />
using System;
using Examen2doPWA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen2doPWA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109005203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Examen2doPWA.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioTwitter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Participantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Leonel",
                            Avatar = "https://fifpro.org/media/5chb3dva/lionel-messi_imago1019567000h.jpg?rxy=0.32986930611281567,0.18704579979466449&rnd=133378758718600000",
                            Email = "goat@utleon.edu.mx",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Messi",
                            Ocupacion = "Desarrollador Full Stack",
                            UsuarioTwitter = "https://x.com/leomessisite?lang=es"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Penaldo",
                            Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAWRTlPgbJmYTdG6UEyeU9cUlBlHHcpccfDEPuM8PRDSoioEf-fquWcWsyfbLCv-w9Mpv4RbHmzauIabXPWce7uzXiGyvkveXkELLUr0Q&s=10",
                            Email = "penaldo@utleon.edu.mx",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "CR7",
                            Ocupacion = "Generador de penales",
                            UsuarioTwitter = "https://x.com/Cristiano"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Sanchez",
                            Avatar = "https://www.infobae.com/resizer/v2/UPGSJ35VNJDRFI6Y3II4QNQYVE.jpg?auth=e000c19b39b8d9fd3742fba0f250e843d8c3d38f14e62d49b70643278f9ee4a6&smart=true&width=350&height=197&quality=85",
                            Email = "78643@utleon.edu.mx",
                            FechaRegistro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "balderas",
                            Ocupacion = "DevOps Engineer",
                            UsuarioTwitter = "https://x.com/NachoAmbriz1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
